#!/bin/sh

if echo "$KUBECONFIG" | base64 -d 2> /dev/null > /tmp/kubeconfig
then
	export KUBECONFIG=/tmp/kubeconfig
fi

if [ "$1" = "sh" ] || [ "$1" = "/bin/sh" ]
then
	exec "$@"
elif [ "$1" = "kubectl" ]
then
	shift
elif [ $# = 0 ]
then
	set -- proxy
fi

mkdir -p /etc/service/kubectl
cat > /etc/service/kubectl/run <<EOF
#!/bin/sh
# a friendly information blob what cluster the active context points to
kubectl cluster-info
# exec is required by runsv otherwise pid:s don't align up as expected
exec kubectl $*
EOF
chmod +x /etc/service/kubectl/run

set -- runsvdir /etc/service
exec "$@"
